# Generated by Django 5.2.6 on 2025-11-19 23:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('local', models.CharField(choices=[('BLOCO_A', 'Bloco A'), ('BLOCO_B', 'Bloco B'), ('BLOCO_C', 'Bloco C'), ('BLOCO_D', 'Bloco D'), ('BLOCO_E', 'Bloco E'), ('BLOCO_F', 'Bloco F'), ('BLOCO_G', 'Bloco G'), ('BLOCO_H', 'Bloco H'), ('BLOCO_J', 'Bloco J'), ('CANTINA', 'Cantina'), ('BIBLIOTECA', 'Biblioteca'), ('BLOCO_I', 'Bloco I'), ('BLOCO_II', 'Bloco II'), ('BLOCO_III', 'Bloco III'), ('PRAINHA', 'Prainha')], max_length=20)),
                ('data_encontro', models.DateField(default=datetime.date.today)),
                ('estado', models.CharField(choices=[('NOVO', 'Novo/Intacto'), ('USADO', 'Usado'), ('DANIFICADO', 'Danificado')], max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='objetos/fotos')),
                ('entregue', models.BooleanField(default=False)),
            ],
        ),
    ]
