# Generated by Django 5.2.6 on 2025-11-26 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objetos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objeto',
            name='entregue',
        ),
        migrations.RemoveField(
            model_name='objeto',
            name='estado',
        ),
        migrations.AddField(
            model_name='objeto',
            name='contato',
            field=models.CharField(blank=True, help_text='WhatsApp para contato', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='objeto',
            name='dono',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='objeto',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('DEVOLVIDO', 'Devolvido'), ('OCULTADO', 'Ocultado')], default='ATIVO', max_length=20),
        ),
        migrations.AddField(
            model_name='objeto',
            name='tipo',
            field=models.CharField(choices=[('ELETRONICOS', 'Eletrônicos'), ('CHAVES', 'Chaves'), ('CARTEIRA', 'Carteira'), ('DOCUMENTOS', 'Documentos'), ('VESTUARIO', 'Vestuário'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='local',
            field=models.CharField(choices=[('BLOCO_A', 'Bloco A'), ('BLOCO_B', 'Bloco B'), ('BLOCO_C', 'Bloco C'), ('BLOCO_D', 'Bloco D'), ('BLOCO_E', 'Bloco E'), ('BLOCO_F', 'Bloco F'), ('BLOCO_G', 'Bloco G'), ('BLOCO_H', 'Bloco H'), ('BLOCO_I', 'Bloco I'), ('BLOCO_II', 'Bloco II'), ('BLOCO_III', 'Bloco III'), ('BLOCO_IV', 'Bloco IV'), ('REITORIA', 'Reitoria'), ('RU', 'Restaurante Universitário'), ('PRAINHA', 'Prainha'), ('BALA_I', 'Bala I'), ('BALA_II', 'Bala II')], max_length=20),
        ),
    ]
