# Generated by Django 5.2.6 on 2025-11-26 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objetos', '0002_remove_objeto_entregue_remove_objeto_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='objeto',
            name='situacao',
            field=models.CharField(choices=[('ACHADO', 'Encontrei (Achado)'), ('PERDIDO', 'Perdi (Perdido)')], default='ACHADO', max_length=10),
        ),
    ]
